j<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>


---

## Домашнее задание 2: библиотека Numpy и линейная алгебра


Импортируем библиотеки:

In [2]:
import numpy as np
import pandas as pd
import matplotlib as pyplot

from scipy import ndimage  # спецификатор для работы с изображениями
from scipy import misc 
from PIL import Image

%matplotlib inline

*Вопросы для самопроверки:*
1. Что такое NumPy?
2. Зачем используется и почему работает быстрее?
3. Что такое линейная алгебра?
4. Как она связана с машинным обучением и глубоким обучением?

### Задание 1

В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [83]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j), здесь i -- число строк,
# j -- число столбцов.
a = np.random.sample((10,10))
b = np.random.sample((10,10))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(np.ndim(a))
print(np.ndim(b))
print(np.shape(a))
print(np.shape(b))
# ========
print(a)
print(b)

2
2
(10, 10)
(10, 10)
[[ 0.63088785  0.10210146  0.84505604  0.185129    0.41289879  0.29298075
   0.46347357  0.82951168  0.00337663  0.82115816]
 [ 0.49559464  0.71651651  0.47104604  0.79932099  0.04729997  0.66235509
   0.46592035  0.09038085  0.10774547  0.04898012]
 [ 0.58988013  0.35321863  0.17251189  0.03140226  0.92293243  0.68286557
   0.80061821  0.87747707  0.55981351  0.60316702]
 [ 0.99630353  0.01656445  0.12329522  0.56841803  0.12323629  0.82403314
   0.2456343   0.34847505  0.27807103  0.79043621]
 [ 0.55103384  0.67884698  0.95903664  0.99563862  0.38401826  0.37601647
   0.26962771  0.85862724  0.68848255  0.92245446]
 [ 0.17035822  0.03883634  0.36851293  0.64589542  0.05955813  0.99939432
   0.49140728  0.57047931  0.82086265  0.61346367]
 [ 0.09320399  0.23342998  0.20125177  0.0914146   0.74674141  0.30401123
   0.79928394  0.30258784  0.10493187  0.62501102]
 [ 0.71892366  0.21995742  0.15613267  0.48268811  0.99791823  0.8644441
   0.61261838  0.19697491  0.5

In [84]:
def mult(a,b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат 
    c=np.zeros(((a.shape[0]),(b.shape[1])))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                c[i,j] += a[i,k] * b[k,j]
    return(c)
mult(a,b)

array([[ 2.22461215,  2.61667843,  2.55259238,  2.64070012,  2.71348698,
         1.74056057,  2.71894615,  2.26454942,  2.41912485,  2.40400828],
       [ 2.19865424,  1.61173209,  2.02767111,  2.2219703 ,  2.14960513,
         1.57190768,  2.04165649,  2.07218789,  1.53404073,  2.57839194],
       [ 2.07506481,  2.70055833,  2.95515113,  2.47625253,  3.22690915,
         2.01339913,  3.27426651,  2.68379021,  2.46241812,  3.96034768],
       [ 2.1802949 ,  1.59425593,  2.83686152,  2.23417113,  2.43662232,
         1.77642423,  2.28557791,  2.43559707,  1.84684389,  2.56911845],
       [ 3.17391719,  3.62694567,  3.81559888,  3.70213446,  3.8375379 ,
         2.42955891,  4.07007547,  3.26969302,  2.75993314,  3.57332529],
       [ 2.16472784,  2.04821875,  2.98936433,  1.96016925,  2.27156004,
         1.07330228,  2.99480063,  1.88636417,  1.57608881,  2.76605003],
       [ 1.33657614,  1.77523476,  1.66615945,  1.68904774,  2.13771679,
         1.15118148,  2.20992336,  1.63015428

In [85]:
import numpy as np
def np_mult(a,b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    c=np.dot(a,b)
    print(c)
    pass
np_mult(a,b)

[[ 2.22461215  2.61667843  2.55259238  2.64070012  2.71348698  1.74056057
   2.71894615  2.26454942  2.41912485  2.40400828]
 [ 2.19865424  1.61173209  2.02767111  2.2219703   2.14960513  1.57190768
   2.04165649  2.07218789  1.53404073  2.57839194]
 [ 2.07506481  2.70055833  2.95515113  2.47625253  3.22690915  2.01339913
   3.27426651  2.68379021  2.46241812  3.96034768]
 [ 2.1802949   1.59425593  2.83686152  2.23417113  2.43662232  1.77642423
   2.28557791  2.43559707  1.84684389  2.56911845]
 [ 3.17391719  3.62694567  3.81559888  3.70213446  3.8375379   2.42955891
   4.07007547  3.26969302  2.75993314  3.57332529]
 [ 2.16472784  2.04821875  2.98936433  1.96016925  2.27156004  1.07330228
   2.99480063  1.88636417  1.57608881  2.76605003]
 [ 1.33657614  1.77523476  1.66615945  1.68904774  2.13771679  1.15118148
   2.20992336  1.63015428  1.28515652  2.32650922]
 [ 2.2737036   2.31172167  3.05605026  2.82713428  3.30285883  2.05586552
   3.13956311  2.79575405  2.15962792  3.80169016]


In [86]:
%%time
# засечем время работы функции без NumPy
mult(a,b)

CPU times: user 1.06 ms, sys: 0 ns, total: 1.06 ms
Wall time: 1.07 ms


array([[ 2.22461215,  2.61667843,  2.55259238,  2.64070012,  2.71348698,
         1.74056057,  2.71894615,  2.26454942,  2.41912485,  2.40400828],
       [ 2.19865424,  1.61173209,  2.02767111,  2.2219703 ,  2.14960513,
         1.57190768,  2.04165649,  2.07218789,  1.53404073,  2.57839194],
       [ 2.07506481,  2.70055833,  2.95515113,  2.47625253,  3.22690915,
         2.01339913,  3.27426651,  2.68379021,  2.46241812,  3.96034768],
       [ 2.1802949 ,  1.59425593,  2.83686152,  2.23417113,  2.43662232,
         1.77642423,  2.28557791,  2.43559707,  1.84684389,  2.56911845],
       [ 3.17391719,  3.62694567,  3.81559888,  3.70213446,  3.8375379 ,
         2.42955891,  4.07007547,  3.26969302,  2.75993314,  3.57332529],
       [ 2.16472784,  2.04821875,  2.98936433,  1.96016925,  2.27156004,
         1.07330228,  2.99480063,  1.88636417,  1.57608881,  2.76605003],
       [ 1.33657614,  1.77523476,  1.66615945,  1.68904774,  2.13771679,
         1.15118148,  2.20992336,  1.63015428

In [87]:
%%time
# засечем время работы функции с NumPy
np_mult(a,b)

[[ 2.22461215  2.61667843  2.55259238  2.64070012  2.71348698  1.74056057
   2.71894615  2.26454942  2.41912485  2.40400828]
 [ 2.19865424  1.61173209  2.02767111  2.2219703   2.14960513  1.57190768
   2.04165649  2.07218789  1.53404073  2.57839194]
 [ 2.07506481  2.70055833  2.95515113  2.47625253  3.22690915  2.01339913
   3.27426651  2.68379021  2.46241812  3.96034768]
 [ 2.1802949   1.59425593  2.83686152  2.23417113  2.43662232  1.77642423
   2.28557791  2.43559707  1.84684389  2.56911845]
 [ 3.17391719  3.62694567  3.81559888  3.70213446  3.8375379   2.42955891
   4.07007547  3.26969302  2.75993314  3.57332529]
 [ 2.16472784  2.04821875  2.98936433  1.96016925  2.27156004  1.07330228
   2.99480063  1.88636417  1.57608881  2.76605003]
 [ 1.33657614  1.77523476  1.66615945  1.68904774  2.13771679  1.15118148
   2.20992336  1.63015428  1.28515652  2.32650922]
 [ 2.2737036   2.31172167  3.05605026  2.82713428  3.30285883  2.05586552
   3.13956311  2.79575405  2.15962792  3.80169016]


### Задание 2

Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.
Аналогично -- с помощью библиотеки NumPy и без нее. Сравните скорость, объясните результат.

In [163]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    B = np.cumsum(A)
    s = len(A) + 1
    C = np.arange(1,(len(A) + 1))
    return (B / C)
    # Ваш код здесь
sec_av(A)

array([ 0.61414094,  0.43096096,  0.46267907, ...,  0.50005438,
        0.50005441,  0.50005437])

In [164]:
# функция без NumPy
from scipy import stats as sps
def stupid_sec_av(A):
    S = [0 for i in range(len(A))]
    for i in range(len(A)):
        if i == 0:
            S[0] = A[0]
        else:
            S[i] = S[i-1] + A[i]
        # Ваш код здесь
    for i in range(len(A)):
        S[i] = S[i]/(i+1)
        # Ваш код здесь
    return S

# зададим некоторую последовательность и проверим ее на ваших функциях. 
# Первая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10 ** 7) 

%time S1 = sec_av(A)
%time S2 = stupid_sec_av(A)
#проверим корректность:
np.abs(S1 - S2).sum()

CPU times: user 159 ms, sys: 141 ms, total: 300 ms
Wall time: 340 ms
CPU times: user 10.8 s, sys: 1.3 s, total: 12.1 s
Wall time: 12.7 s


0.0

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться без изменений. В конце требуется слить массив $X$ с преобразованным $X$ и вывести в обратном порядке.

In [206]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    C = X.copy()
    C[::2] = list(map(lambda x: x ** 3, C[::2]))
    C[1::2] = list(map(lambda x: a, C[1::2]))
    n=len(C)//2
    C[:n:2], C[n+1::2] = C[n+1::2], C[:n:2]
    return np.concatenate((X,C))
#решение, которое будет работать быстрее с np.array и с list

In [207]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    C = X.copy()
    for i in range(len(X)):
        if i % 2 != 0:
            C[i] = a
        else:
            C[i] = C[i] ** 3
    n=(len(C)-1)//2*2
    for i in range(n//2):
        if i % 2 == 0:
            C[i], C[n-i] = C[n-i], C[i]  
    return X + C

In [209]:
X = sps.uniform.rvs(size=10 ** 7) 
# здесь код эффективнее примерно в 20 раз. 
# если Вы вдруг соберетесь печатать массив без np -- лучше сначала посмотрите на его размер
%time S1 = transformation(X)
%time S2 = stupid_transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

CPU times: user 6.08 s, sys: 509 ms, total: 6.59 s
Wall time: 6.77 s
CPU times: user 7.58 s, sys: 553 ms, total: 8.13 s
Wall time: 8.22 s


ValueError: operands could not be broadcast together with shapes (20000000,) (10000000,) 

Что вы можете сказать о скорости вычислений в `NumPy`? Ответ обоснуйте.

**Ответ:** цикл с обращением по индексам: np медленнее list
слайсы: np быстрее list
слайсы быстрее цикла по индексам всегда

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [244]:
a = np.random.random(3)
b = np.random.random(3)
print(a,b)

[ 0.48247525  0.25771947  0.00323847] [ 0.5158123   0.28522173  0.88204391]


In [245]:
def stupid_scalar_product(a,b):
    c = 0
    for i in range(len(a)):
        c += a[i] * b[i]
    return c
stupid_scalar_product(a,b)

0.32523033203884394

In [246]:
def numpy_scalar_product(a,b):
    return np.sum(a*b)
numpy_scalar_product(a,b)

0.32523033203884394

In [247]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 60 µs, sys: 124 µs, total: 184 µs
Wall time: 228 µs
CPU times: user 89 µs, sys: 86 µs, total: 175 µs
Wall time: 185 µs


0.0

## Бонусная часть (в тесте вопросов по ней не будет)

Image = 2-D численный массив
(или 3-D: CT, MRI, 2D + time; 4-D, …)
В текущем задании, image == Numpy array (np.array)

In [248]:
pic = misc.face() #встроенная в библиотеку функция, которая загружает картинку с енотом

Выведите тип и размеры для переменной pic. Что лежит внутри?

In [249]:
print(#тут ваш код)

SyntaxError: unexpected EOF while parsing (<ipython-input-249-50b064173985>, line 1)

Если вы все сделали правильно, что для формы у вас выведется кортеж из трех чисел: (X, Y, 3). Предположите, откуда там 3?

**Ответ:**

С помощью функции ниже можно вывести изображение и посмотреть, что находится внутри:

In [0]:
plt.imshow(pic)

Убедитесь, что внутри массива `pic` действительно лежат числа. Выведите первые 10 записей.
Массив состоит из троек чисел, которые характеризуют глубину цвета для каждого пикселя. Из пикселей складывается картинка.

In [0]:
print(#тут ваш код)

Выведите значение максимального элемента в матрице. Выведите значение минимального. Выведите среднее по всем элементам матрице. В каких пределах лежат значения глубины цветов?

In [0]:
print(#тут ваш код)

## Задание 2

Теперь загрузим черно-белое изображение енота, чтобы наш массив был не 3-х мерным тензором, а двумерным массивом. Тензоры обрабатываются точно также, но для простоты пока что давайте работать с двумерными массивами, т.е. матрицами.

In [0]:
pic = misc.face(gray=True)

In [0]:
plt.imshow(#тут ваш код)

Выведите форму (shape) полученной картинки `pic`. Какие выводы можно сделать? Положите в `h`,`w` высоту и ширину картинки.

In [0]:
print(#тут ваш код)
h,w=#тут ваш код

Используя библиотеку `numpy`, отразите изображение по горизонтали. Выведите картинку.

Подсказка: не забывайте, что изображения -- это просто двумерные массивы

In [0]:
#тут ваш код

Теперь давайте повысим контрастность -- для этого к каждому пикселю прибавим 50 единиц

In [0]:
#тут ваш код

In [0]:
plt.imshow(pic)

Теперь давайте попробуем превратить наше одноканальное изображение в трехканальный (RGB) тензор. Для этого вместо каждого пикселя в одноканальном изображении (в двумерном массиве) поставим кортеж из трех элементов -- глубины красного, зеленого и голубого соотвественно. Восстановить по ч/б картинке цветной мы не можем, так как мы не можем взять утерянную информацию из ниоткуда, но можем усилить черные и белые участки. Для этого давайте заполним все три канала одинаковыми значениями, деленными на что-то очень большое. Например $--$ на $200$.  То есть, например, если в пикселе `pic[i][j]` лежало значение **200**, то для нового изображения `new_pic` мы заполняем `new_pic[i][j]` кортежем из трех чисел `int(pic[i][j]/3)`. Функция `int` $--$ округление до целой части.

In [0]:
new_pic = np.zeros((h,w,3)) #создадим пустую матрицу, куда будем записывать значения
for i in range(h):
    for j in range(w):
     #тут ваш код

In [0]:
plt.imshow(#тут ваш код)

## Задание 3

Теперь давайте уменьшим качество картинки в 16 раз, путем уменьшения качества изображения, т.е. теперь 16 пикселей по близости надо заполнить одним значением.

In [0]:
from sklearn.datasets import load_sample_image #импорт загрузчика изображения

In [0]:
china = load_sample_image('china.jpg')
plt.imshow(china)

Запишите в переменные `h`, `w`, `c` высоту, ширину, количество каналов соответственно для картинки `china`.

In [0]:
h, w, c = #тут ваш код

Теперь давайте непосредственно перейдем к изменению картинки $--$ мы предлагаем разбивать картинки на квадраты 4 на 4 и заполнять все 16 значений внутри квадрата левым верхним значением. Вы можете сделать иначе.

In [0]:
from copy import copy
compressed_pic = copy(china)
#тут ваш код     

Напишите функцию, которая считает несоотвествие между исходной и сжатой картинкой. Запустите ваш код для `compressed_pic`, `china`

In [0]:
def calculate_mismatch(a,b):
    mismatch=0
    #тут ваш код
    print(mismatch)

In [0]:
calculate_mismatch(#тут ваш код)

Посчитайте синус от каждого значения пикселей изображения `china` по всем каналам. Выведите картинку. Используйте функцию `np.sin` 

In [0]:
#тут ваш код

In [0]:
plt.imshow(#тут ваш код) 

Посмотрите на полученный результат. Как вы думаете, что можно делать с помощью такого преобразования? Какого рода объекты можно распознать?

### Задание 4*
это задание является дополнительным

Теперь давайте поработаем с аудиофайлами. Стандартный аудиофайл представляет собой обычный набор чисел, в котором хранятся значения частот, снятых с определенной периодичностью. Итак, самая простая аудиодорожка $-$ одномерный массив.

Первое, что нужно сделать $--$ установить библиотеку для работы с аудио. Она называется `librosa`. Гайд по установке: https://librosa.github.io/librosa/install.html


In [0]:
import librosa #импортируем библиотеку
import IPython.display

In [0]:
audio, sr= librosa.load('Test.wav')  
# записываем наш массив звуковых частот в файл аудио, sr -- число точек, записываемых в секунду. 
# чтобы файл открылся, он должен лежать в той же папке, что и файл HW_2.ipynb

Нашу дорожку можно воспроизвести в самом файле `.ipynb`:

In [0]:
IPython.display.Audio(audio, rate=sr)

Выведите тип данных переменной `audio`, найдите ее длительность и среднее.

In [0]:
print(#тут ваш код)

    Давайте посмотрим, как выглядит наша дорожка. Для этого используем библиотеку `matplotlib.pyplot`

In [0]:
plt.figure(figsize=(25,5))
plt.title('Test.wav')
plt.plot(audio)

Обрежьте последние 4 секунды файла

In [0]:
audio = #тут ваш код

Давайте уменьшим амплитуду на 25%. Что при этом изменится? Напоминаю, что вы всегда можете послушать изменения при помощи `IPython.display.Audio`

In [0]:
audio = #тут ваш код

А еще аудиодорожку можно ускорить. Для этого попробуйте потюнить параметр `rate`

In [0]:
IPython.display.Audio(audio, rate=sr)